### ISSUE TITLE
Chilling blade lost its unique slow effects

### ISSUE THREAD

**Issue by faxsi** [Stardust-Labs-MC/Incendium#35] opened 2023-04-02 12:14 UTC
is there a way to get the chilling blade slowness effect back? all my friends who got the chilling blade suddenly dont have the slowness effect. even with unenchanted chilling blade
at first it slows mobs and players and then suddenly gone after several server crash
running on paper 1.19.3

https://github.com/Stardust-Labs-MC/Incendium/issues/34

**Comment by catter1** [comment] 2023-04-02 12:44
Duplicate of #34

**Closed by catter1** 2023-04-02 12:44 UTC
Labels: duplicate
